baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gregdaynes.com" # the base hostname & protocol for your site, e.g. http://example.com
incremental: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-compose
  - jekyll-contentblocks
  - hyde-page-css
  - hyde-page-js
  - hyde-page-html
  - hyde-decap

hyde_page_css:
  minify: false
  keep_files: true
  livereload: true

hyde_page_js:
  keep_files: true
  dev_mode: true

hyde_page_html:
  enable: true
  validate: false
  validator_uri: 'http://0.0.0.0:8888/'
  beautify: true
  minify: true

hyde_decap:
  keep_files: false
  enabled: true
  backend:
    name: github
    repo: gregdaynes/gregdaynes.github.io # github path to repo
    site_domain: gregdaynes.github.io # site name
    branch: main # Branch to update (optional; defaults to master)
  local_backend: true
  publish_mode: editorial_workflow
  media_folder: "src/images/uploads" # Media files will be stored in the repo under images/uploads
  public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
  collections:
  - label: Advertisements
    name: advertisements
    folder: _data/advertisements
    label_singular: Advertisement
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
  - label: icons
    name: icons
    folder: _includes/icons
    create: true
    extension: svg
    format: yaml-frontmatter
    frontmatter_delimiter:
    - "<!--"
    - "-->"
    fields:
    - label: Title
      name: title
      widget: string
    - label: Body
      name: body
      widget: text
  - label: Navigation
    name: navigation
    create: true
    folder: _data/navigation
    extension: yml
    format: yaml-frontmatter
    fields:
    - label: Title
      name: title
      widget: string
    - label: Data
      name: data
      widget: list
      fields:
      - label: Text
        name: text
        widget: string
      - label: Href
        name: href
        widget: string
      - label: Icon
        name: icon
        widget: relation
        collection: icons
        required: false
        value_field: title
        search_fields:
        - title
  - label: Skills
    name: skills
    label_singular: skill
    folder: _data/skills
    create: true
    identifier_field: name
    extension: yml
    format: yaml-frontmatter
    fields:
    - label: Name
      name: name
      widget: string
    - label: data
      name: data
      widget: list
      collapsed: true
      allow_add: true
      fields:
      - label: Title
        name: title
        widget: string
      - label: Subtitle
        name: subtitle
        widget: string
        required: false
      - label: Content
        name: content
        widget: markdown
        required: false
      - label: Date Start
        name: datestart
        widget: datetime
        required: false
        default: ''
      - label: Date End
        name: dateend
        widget: datetime
        required: false
        default: ''
      - label: Level
        name: level
        widget: number
        value_type: int
        min: 1
        max: 5
        required: false
      - label: Notes
        name: notes
        label_singular: note
        widget: list
        required: false
        collapsed: true
        field:
          widget: string
          name: note
          required: false
  - label: Pages
    name: pages
    label_singular: page
    folder: _data/pages
    extension: yml
    format: yaml-frontmatter
    create: true
    identifier_field: name
    fields:
    - label: Name
      name: name
      widget: string
    - label: Subtitle
      name: subtitle
      widget: string
      required: false
    - label: Content
      name: content
      widget: markdown
      required: false
  - name: posts
    label: Posts
    folder: _posts/
    label_singular: Post
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    description: test description
    fields:
    - label: Layout
      name: layout
      widget: hidden
      default: post
    - label: Title
      name: title
      widget: string
    - label: Categories
      name: categories
      widget: relation
      collection: "resources"
      file: 'categories'
      search_fields:
        - "data.*.title"
      display_fields:
        - "data.*.title"
      value_field: "data.*.title"
      multiple: true
      min: 1
    - label: Excerpt
      name: excerpt
      widget: markdown
    - label: Tags
      name: tags
      widget: relation
      collection: "resources"
      file: 'tags'
      search_fields:
        - "data.*.title"
      display_fields:
        - "data.*.title"
      value_field: "data.*.title"
      multiple: true
      min: 1
    - label: Topic
      name: topic
      widget: object
      required: false
      fields:
      - label: title
        name: title
        widget: string
        required: false
      - label: author
        name: author
        widget: string
        required: false
      - label: link
        name: link
        widget: string
        required: false
      - label: archive
        name: archive
        widget: string
        required: false
    - label: Body
      name: body
      widget: markdown
  - name: resources
    label: Resources
    files:
    - label: Categories
      name: categories
      file: _data/categories.yml
      fields:
      - label: data
        name: data
        widget: list
        fields:
        - label: Title
          name: title
          widget: string
    - label: Tags
      name: tags
      file: _data/tags.yml
      create: true
      fields:
      - label: data
        name: data
        widget: list
        fields:
        - label: Title
          name: title
          widget: string
    - label: Fonts
      name: fonts
      file: _data/fonts.yml
      fields:
      - label: Fonts
        name: fonts
        widget: object
        fields:
        - label: Faces
          name: faces
          widget: list
          collapsed: false
          create: true
          fields:
          - label: Name
            name: name
            widget: string
          - label: Provider
            name: provider
            widget: string
            default: google
          - label: Weights
            name: weights
            widget: list
            collapsed: false
            fields:
            - label: Weight
              name: value
              widget: string
            - label: Italic
              name: italic
              widget: boolean
