baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gregdaynes.com" # the base hostname & protocol for your site, e.g. http://example.com
incremental: true

analytics: http://localhost:4000

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-compose
  - jekyll-contentblocks
  - hyde-page-css
  - hyde-page-js
  - hyde-page-html

hyde_page_css:
  minify: false
  keep_files: true
  livereload: true

hyde_page_js:
  keep_files: true
  dev_mode: true

hyde_page_html:
  enable: true
  validate: false
  validator_uri: 'http://0.0.0.0:8888/'
  beautify: true
  minify: true
